services:
  markitdown-web-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markitdown-web-ui-dev
    ports:
      - "8200:8200"  # Expose port 8200 to local PC
    volumes:
      # Configurable input/output folder mapping
      - ${INPUT_DIR:-./uploads}:/app/uploads:rw
      - ${OUTPUT_DIR:-./output}:/app/output:rw
      - ./logs:/app/logs:rw
      - ./input:/app/input:rw
      # Development: Mount source code for live reloading
      - ./packages:/app/packages:ro
      - markitdown_cache:/app/cache
      - markitdown_ocr_cache:/app/ocr_cache
    environment:
      - HOST=0.0.0.0
      - PORT=8200
      - INPUT_DIR=/app/uploads
      - OUTPUT_DIR=/app/output
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app/packages/markitdown-web-ui/src:/app/packages/markitdown-mcp-server/src
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - markitdown-network

networks:
  markitdown-network:
    driver: bridge

volumes:
  markitdown_cache:
    driver: local
  markitdown_ocr_cache:
    driver: local
