[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "markitdown-web-ui"
dynamic = ["version"]
description = "Web UI for MarkItDown file conversion"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["markitdown", "web-ui", "fastapi", "file-conversion"]
authors = [
  { name = "MarkItDown Team", email = "team@markitdown.dev" },
]

dependencies = [
  "fastapi>=0.100.0",
  "uvicorn[standard]>=0.20.0",
  "jinja2>=3.1.0",
  "python-multipart>=0.0.6",
  "markitdown>=0.1.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-asyncio>=0.21.0",
  "httpx>=0.25.0",
  "black>=23.0.0",
  "isort>=5.12.0",
  "mypy>=1.0.0",
  "ruff>=0.1.0",
]

[project.scripts]
markitdown-web = "markitdown_web_ui.app:main"

[tool.hatch.version]
path = "src/markitdown_web_ui/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/markitdown_web_ui"]

[tool.black]
line-length = 88
target-version = ['py310', 'py311', 'py312']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[tool.ruff]
target-version = "py310"
line-length = 88
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
  "UP", # pyupgrade
]
ignore = [
  "E501",  # line too long, handled by black
  "B008",  # do not perform function calls in argument defaults
  "C901",  # too complex
]

